# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cserver.proto\x12\x07\x65xample\"\x17\n\x07request\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x18\n\x05reply\x12\x0f\n\x07message\x18\x01 \x01(\t27\n\x06Server\x12-\n\x07handler\x12\x10.example.request\x1a\x0e.example.reply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=25
  _REQUEST._serialized_end=48
  _REPLY._serialized_start=50
  _REPLY._serialized_end=74
  _SERVER._serialized_start=76
  _SERVER._serialized_end=131
# @@protoc_insertion_point(module_scope)
